app:
  apiKey: $OPENAI_API_KEY
  host: "$HOST:0.0.0.0"
  port: "$PORT:8080"
  mcpGatewayImage: "$MCP_GATEWAY_IMAGE:docker/mcp-gateway:latest"
  weatherApiUrl: "$WEATHER_API_URL:https://api.open-meteo.com/v1/forecast"